import './globals.css'
import { Inter } from 'next/font/google'
import {cookies} from "next/headers";
import Login from "@biddingnew/components/login";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const loginFunction = async (user: string) => {
    "use server";
    // @ts-ignore
    cookies().set('login', user);
    return true;
  }
  // @ts-ignore
  const login = cookies().get('login');

  return (
    <html lang="en">
      <body className={inter.className}>{login ? children : <Login setLogin={loginFunction} />}</body>
    </html>
  )
}
